name: Flutter CI (auto-detect project)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo tree (debug)
        run: |
          echo "=== repo root files ==="
          ls -la
          echo ""
          echo "=== git tracked pubspec.yaml files ==="
          git ls-files '*pubspec.yaml' || true

      - name: Detect Flutter project directory
        id: detect
        run: |
          # Find first tracked pubspec.yaml (prefer tracked files)
          PUBSPEC=$(git ls-files '*pubspec.yaml' | head -n 1 || true)
          if [ -z "$PUBSPEC" ]; then
            echo "No pubspec.yaml found in repo. Failing early."
            exit 1
          fi
          PROJ_DIR=$(dirname "$PUBSPEC")
          echo "Found pubspec at: $PUBSPEC"
          echo "PROJECT_DIR=$PROJ_DIR" >> $GITHUB_ENV
          echo "::set-output name=project_dir::$PROJ_DIR"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Disable Flutter analytics (non-interactive)
        run: |
          flutter config --no-analytics || true
          flutter --version

      - name: Cache pub & dart tool
        uses: actions/cache@v3
        with:
          # Cache based on all pubspec.yaml files in the repo (works for subfolders)
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
          path: |
            ~/.pub-cache
            .pub-cache
            **/.dart_tool

      - name: Get dependencies (in project dir)
        run: |
          echo "PROJECT_DIR=${PROJECT_DIR}"
          cd "${PROJECT_DIR}"
          flutter pub get
        env:
          PUB_CACHE: ${{ runner.tool_cache }}/pub-cache

      - name: Validate formatting (in project dir)
        run: |
          cd "${PROJECT_DIR}"
          flutter format --set-exit-if-changed .

      - name: Analyze code (in project dir)
        run: |
          cd "${PROJECT_DIR}"
          flutter analyze

      - name: Run tests (in project dir)
        run: |
          cd "${PROJECT_DIR}"
          flutter test --no-publish-platform-views
